live:
  db:
    adapter: Pdo_Mysql
    params:
      host: 127.0.0.1
      dbname: fschack
      username: root
      password:

alpha:
  _extends: live
  db:
    params:
      dbname: fschack
      username: root
      password:
