home:
  label: Home
  controller: index
investigations:
  label: View investigations
  controller: investigation
sites:
  label: View sites
  controller: site
import:
  label: Import data
  controller: upload